name: Build
on:
  push:
    paths-ignore:
    - 'docs/**'

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sh configure
    - name: make
      run: make
    - name: test
      run: make Test


